### PR TITLE
Fixed NPE caused by new embed response from YT

### PR DESCRIPTION
**Pull request by Walkyst**
Now youtube starting sending sometimes new response on embed page in that case we getting NPE, this PR fixing this

### CODE REVIEW

**Comment by Walkyst** [comment]
Don't acccept this PR i found other issue

**Comment by Walkyst** [comment]
Now this PR is fine

**Review by devoxin — APPROVED** [review]

**Comment by devoxin** [comment]
This needs to target dev branch

**Comment by freyacodes** [comment]
> This needs to target dev branch

You can change the target yourself by pressing the edit button.

**Comment by devoxin** [comment]
Yeah, just got a warning about old commits which made me a bit cautious, heh.

**Comment by Walkyst** [comment]
> This needs to target dev branch

Done

**Pull request merged**
