### PR TITLE
Optimized requesting in REQUIRES_LOGIN case

### PR DESCRIPTION
**Pull request by Walkyst**
If we try to play age-restricted video lavaplayer doing two requests of embed page, this PR optimizing this use case

### CODE REVIEW

**Comment by devoxin** [comment]
Is there any scenario where an age restricted video doesn't include the baseJs? I'm curious, as the `baseJs` parameter is still filled in with the asset from the initial page request.

A quick glance at the code suggests that if the baseJs isn't included, it will break because it doesn't use the JS file from the embed page if available.

**Comment by Walkyst** [comment]
> Is there any scenario where an age restricted video doesn't include the baseJs? I'm curious, as the `baseJs` parameter is still filled in with the asset from the initial page request.

In my tests age restricted videos now always send new json and don't include baseJs.
As i said in previus PR embed page always have baseJs.
> A quick glance at the code suggests that if the baseJs isn't included, it will break because it doesn't use the JS file from the embed page if available.

Why? baseJs includes from embed page and it's being used.
And you can always test this PR yourself on bot
@Devoxin

**Comment by Walkyst** [comment]
So, any updates on this?

**Comment by devoxin** [comment]
Oops yeah sorry, forgot about this and have been busy. In your PR, the line below `REQUIRES_LOGIN` is always set to use the baseJs from the initial request, rather than from the embed page. This is what I meant, and seems like it could be problematic?

**Comment by Walkyst** [comment]
If initial request don't have baseJs we use it from embed page and as i said age restricted videos don't have baseJs in initial request

```
    if (baseJs.isNull()) {
      return info.get("assets").get("js").text();
    }
```

**Comment by devoxin** [comment]
Ah right I'm understanding now, sorry. The embed page always includes `assets/js` so it'll always use that one for age restricted videos. LGTM

**Review by devoxin — APPROVED** [review]

**Pull request merged**
